version: '3.8'

services:
  postgres:
    image: postgres:14.23-alpine3.24
    container_name: postgres_db
    environment:
      POSTGRES_DB: yourdb
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chatterbox_backend

  redis:
    image: redis:8.4-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - chatterbox_backend

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    ports:
      - "5540:5540"
    networks:
      - chatterbox_backend
    depends_on:
      - redis

volumes:
  postgres_data:

networks:
  chatterbox_backend:
    driver: bridge